name: Docker Test

on:
  push:
    branches: [ "test/docker" ]
  pull_request:
    branches: [ "test/docker" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        MONGO_PASS: ${{ secrets.MONGO_PASS }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test with selenium
      run: |
        pip install pytest selenium
        pytest Education_Pathways/tests/test_sv_frontend.py
